server:
  port: 8080
  forward-headers-strategy: native

spring:

  security:
    oauth2:
      authorizationserver:
        issuer: http://auth.localhost

  datasource:
    hikari:
      jdbc-url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      minimum-idle: ${MINIMUM_IDLE}
      maximum-pool-size: ${MAXIMUM_POOL_SIZE}

  jpa:
    open-in-view: false

  web:
    resources:
      add-mappings: false

logging:
  level:
    org:
      hibernate:
        orm:
          connections:
            pooling: warn

